Add antidiscrimination toast to mafiasi and notice to footer
fsinfuhh/mafiasi pull request #183
Opened 2024-11-22 11:03 UTC by lilioid

The toast disappears when clicked/touched and after 20 seconds.

On Desktop:
![image](https://github.com/user-attachments/assets/a5598aee-181b-4101-a95a-7e5c9e2ee347)

On mobile:
![image](https://github.com/user-attachments/assets/a823c871-ab80-4f63-ab74-f3e68d440504)

2024-11-22 13:41 UTC, timonegk approved these changes

2024-11-22 16:34 UTC, lilioid commented
@timonegk Möchtest du noch eine französische Version hinzufügen?

2024-11-27 13:45 UTC, MarkusNeblung approved these changes

2024-11-27 19:04 UTC, kritzl approved these changes

2024-11-29 14:03 UTC, Wahlord requested changes
Wie wir gerade auf dem Mafiasi-AG-Treffen diskutiert haben, möchten wir den Text wie folgt ändern:

> Auf Mafiasi.de ist kein Platz für Diskriminierung und Menschenfeindlichkeit in jeder Form (vgl. Art. 3 GG). 

Art.3 GG kann auch gerne auf den Artikel verlinken.
Für die Gründe siehe Protkoll vom 29.11.2024

2024-11-29 14:09 UTC, Wahlord commented
"There is no place for discrimination in any way shape or form at mafiasi.de (cmp. <a href="https://www.gesetze-im-internet.de/englisch_gg/englisch_gg.html#p0027" rel=\"external\">Art. 3 GG</a>).<br> If you are afflicted, feel free to contact the <a href=\"mailto:fsr-vertraulich@informatik.uni-hamburg.de\">student council</a> or the university's <a href=\"https://www.uni-hamburg.de/antidiskriminierung.html\" rel=\"external\">anti-discrimination office</a> ."

2025-02-17 14:25 UTC, lilioid commented
Looks like this now:
![image](https://github.com/user-attachments/assets/306299a4-2f1d-4f3a-ac61-fb64f5317b29)

---

Mobile banner has been removed as was discussed with FSR.

2025-02-17 14:54 UTC, Wahlord approved these changes

2025-02-17 14:57 UTC, merged