Darkmode & Style fixes
fsinfuhh/mafiasi pull request #99
Opened 2022-12-15 21:13 UTC by kritzl

2022-12-15 21:14 UTC, kritzl commented on mafiasi/base/templates/base.html
> +    <script>
This render blocking script-tag is required to prevent the page from flashing in a wrong theme

2022-12-15 21:16 UTC, kritzl commented on mafiasi/base/templates/base.html
> +    </script>
This render blocking script-tag is required to prevent the page from flashing in a wrong theme

2022-12-15 21:19 UTC, kritzl commented on mafiasi/dashboard/templates/dashboard/index.html
> +        </h2>
By placing the santa-hat inside the title, we can position it in relation to it.

2022-12-15 21:20 UTC, kritzl commented on mafiasi/dashboard/static/css/dashboard-christmas.css
> +    left: -6px;
By using `position: absolute;` we remove the santa-hat from the document flow - this was causing the additional margin.

2022-12-16 11:07 UTC, ftsell requested changes
This all looks good but while we're at fixing the darkmode I have noticed some additional quirks that should be ironed out:

1. The *new* button for adding a group needs better styles
   ![image](https://user-images.githubusercontent.com/12398140/208084885-71a1bee6-45a8-4d86-b1e4-18dc98d5c8b3.png)
2. The gprot page still looks a bit white. maybe the textboxes should have a grey background or something similar
   ![image](https://user-images.githubusercontent.com/12398140/208085176-1c51fe83-d97a-4d43-87ce-bded4e754048.png)
   Like this:
   ![image](https://user-images.githubusercontent.com/12398140/208085278-bbc27a6d-44b8-44a2-82d8-7046209d26db.png)

2022-12-16 12:05 UTC, kritzl commented
> This all looks good but while we're at fixing the darkmode I have noticed some additional quirks that should be ironed out:
> 
> 1. The _new_ button for adding a group needs better styles
>    ![image](https://user-images.githubusercontent.com/12398140/208084885-71a1bee6-45a8-4d86-b1e4-18dc98d5c8b3.png)

fixed this in dc641d6 :)

> 2. The gprot page still looks a bit white. maybe the textboxes should have a grey background or something similar
>    ![image](https://user-images.githubusercontent.com/12398140/208085176-1c51fe83-d97a-4d43-87ce-bded4e754048.png)
>    Like this:
>    ![image](https://user-images.githubusercontent.com/12398140/208085278-bbc27a6d-44b8-44a2-82d8-7046209d26db.png)

This error is caused by missing cache busting. We should use it (see https://github.com/fsinfuhh/mafiasi/pull/95#issuecomment-1353726577)

2022-12-16 12:07 UTC, ftsell approved these changes
alright, lgtm then. Merge whenever you're ready

2022-12-16 12:08 UTC, merged

2022-12-16 12:09 UTC, ftsell commented
now we just watch the CI magic happen :))))